dataset: cora
# model
hidden_size: 64
layer_num: 2
activation: relu
dropout: 0.1
model: GNN
encoder: GCN_Encoder
# training
lr: 0.01
weight_decay: 0.005
epochs: 300
earlystop: True
patience: 20

#gcnii
alpha: 0.1
theta: 1

